_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: True
  KEYPOINT_ON: True
  ROI_HEADS:
    NUM_CLASSES: 1
  ROI_BOX_HEAD:
    SMOOTH_L1_BETA: 0.5
  ROI_KEYPOINT_HEAD:
    NUM_KEYPOINTS: 17
  RPN:
    POST_NMS_TOPK_TRAIN: 1500
